# Generated by Django 6.0 on 2025-12-19 20:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('bio', models.TextField(blank=True)),
                ('photo', models.CharField(blank=True, help_text='Path to artist photo in media folder', max_length=500)),
                ('website', models.URLField(blank=True)),
                ('instagram', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('image', models.CharField(help_text='Path to main image in media folder', max_length=500)),
                ('image_detail_1', models.CharField(blank=True, help_text='Path to detail image 1', max_length=500)),
                ('image_detail_2', models.CharField(blank=True, help_text='Path to detail image 2', max_length=500)),
                ('medium', models.CharField(choices=[('oil', 'Oil on Canvas'), ('acrylic', 'Acrylic on Canvas'), ('watercolor', 'Watercolor'), ('mixed', 'Mixed Media'), ('digital', 'Digital Print'), ('photography', 'Photography'), ('sculpture', 'Sculpture')], max_length=20)),
                ('dimensions', models.CharField(help_text='e.g., 36 x 48 inches', max_length=100)),
                ('year', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='gallery.artist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
