# Generated by Django 6.0 on 2025-12-28 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='image_detail_3',
            field=models.CharField(blank=True, help_text='Path to detail image 3', max_length=500),
        ),
    ]
