# Generated by Django 6.0 on 2026-01-02 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_add_image_detail_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
    ]
