# Generated by Django 6.0 on 2025-12-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhibition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('artist_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.CharField(help_text='Path to exhibition image in media folder', max_length=500)),
                ('start_date', models.CharField(help_text="Display date, e.g., 'December 1, 2024'", max_length=50)),
                ('end_date', models.CharField(help_text="Display date, e.g., 'January 15, 2025'", max_length=50)),
                ('location', models.CharField(default='Main Gallery', max_length=200)),
                ('is_current', models.BooleanField(default=False)),
                ('is_upcoming', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'ordering': ['order', '-is_current', '-is_upcoming'],
            },
        ),
    ]
